name: CI

on:
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
      - name: Install dependencies
        run: npm i
      - name: Prettier
        run: npx prettier --check '**/*.{js,jsx,ts,tsx}'
      - name: ESLint
        run: npx eslint --ext .js,.jsx,.ts,.tsx .
      - name: Type check
        run: npx tsc --noEmit
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
      - name: Install dependencies
        run: npm i
      - name: Test with jest
        env:
          CHAINLIT_API_URL: ${{ secrets.CHAINLIT_API_URL }}
          CHAINLIT_API_KEY: ${{ secrets.CHAINLIT_API_KEY }}
        run: npm test
